#!/bin/sh
# -*- mode: sh-script; sh-shell: ash; -*-
# SPDX-FileCopyrightText: Copyright (c) 2024 s-expressionists
# SPDX-License-Identifier: MIT

# Usage:
#
#   bench [IMPLEMENTATION...]

set -o nounset
set -o pipefail
set -o errexit

abcl() {
  printf -- "--- ABCL ----------------------------------------------------------------------\n"
  command abcl --noinform "$@" | sed '/^;/d'
}

ccl() {
  printf -- "--- CCL -----------------------------------------------------------------------\n"
  command ccl "$@"
}

clasp() {
  printf -- "--- Clasp ---------------------------------------------------------------------\n"
  command clasp --noinform "$@" | sed '/^;/d'
}

ecl() {
  printf -- "--- ECL -----------------------------------------------------------------------\n"
  command ecl "$@" | sed '/^;;;/d'
}

sbcl() {
  printf -- "--- SBCL ----------------------------------------------------------------------\n"
  command sbcl --noinform "$@" 2>&1 | awk '!keep && /^ +float-integer/ { keep=1; print "" } keep { print }'
}

bench() {
  local ret=0
  for implementation in "$@"; do
    case "$implementation" in
    abcl|ccl|clasp|ecl|sbcl)
      if command -v "$implementation" >/dev/null; then
        "$implementation" \
          --eval '(require "asdf")' \
          --eval '(asdf:load-system "quaviver/benchmark")' \
          --eval '(quaviver/benchmark:float-integer)' \
          --eval '(uiop:quit)' \
          2>/dev/null
        printf "\n"
      else
        printf >&2 "bench: implementation not found: %s\n" "$implementation"
        ret=1
      fi
      ;;
    *)
      printf >&2 "bench: unknown implementation: %s\n" "$implementation"
      ret=1
      ;;
    esac
  done
  return "$ret"
}

if test "$#" -le 0; then
  for implementation in abcl ccl clasp ecl sbcl; do
    if command -v "$implementation" >/dev/null; then
      set -- "$@" "$implementation"
    fi
  done
fi

bench "$@"
